server:
  port: ${PORT:${SERVER_PORT:0}} #这个的意思是随机指定个没使用的端口

spring:
  application:
    name: admin-service
eureka:
  client: 
    serviceUrl:
      defaultZone: http://llahn:llahn@localhost:8890/eureka/